name: HACS Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.1"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          # Will be making pull request for brand icons soon
          ignore: "brands"